name: wallpaper
description: the wallpaper class model and its parser
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
  http: ^1.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

resolution: workspace