name: worker_persistency
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.2

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
