name: dart
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: none

environment:
  sdk: 3.6.2

# Add regular dependencies here.
dependencies:
  http: ^1.3.0
  wallpaper_generator:
    path: ../packages/wallpaper_generator
  wallpaper:
    path: ../packages/wallpaper
  wallpaper_worker:
    path: ../packages/wallpaper_worker

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.0.9
  lints: ^5.0.0