name: wallpaper_generator
description: A wallpaper generator
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  image: ^4.5.2
  wallpaper:
    path: ../wallpaper

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0