name: paths_collection
description: file path collection management
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
  http: ^1.3.0
  worker_persistency:
    path: ../worker_persistency

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
