name: wallpaper_worker
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.2

dependencies:
  http: ^1.3.0
  image: ^4.5.2
  wallpaper_generator:
    path: ../wallpaper_generator
  wallpaper:
    path: ../wallpaper
  worker_database:
    path: ../worker_database

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
