name: Deploy Dart Web App

on:
  push:
    branches:
      - main
      - new-dart-generator
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.6.2

      - name: Install Dependencies
        run: |
          cd dart/web
          dart pub get

      - name: Compile Worker to JavaScript
        run: |
          cd dart
          dart compile js -o web/wallpaper_generator_worker.js lib/workers/wallpaper_generator_worker.dart
          
      - name: Compile Main to JavaScript
        run: |
          cd dart/web
          dart compile js -o main.js main.dart

      - name: Prepare site folder
        run: |
          mkdir -p site
          mkdir -p site/static
          mkdir -p site/static/logos
          mkdir -p site/static/octocats
          mkdir -p site/static/wallpapers
          mkdir -p site/static/backgrounds
          mkdir -p site/static/examples
          mkdir -p site/static/favicons
          mkdir -p site/styles
          mkdir -p site/fonts
          mkdir -p site/scripts
          cp dart/web/index.html site/
          cp dart/web/main.js site/
          cp dart/web/wallpaper_generator_worker.js site/
          cp -r dart/web/scripts/. site/scripts/
          cp -r dart/web/styles/. site/styles
          cp -r dart/web/fonts/. site/fonts
          cp -r static/favicons/. site/static/favicons
          cp -r static/logos/. site/static/logos/
          cp -r static/octocats/. site/static/octocats/
          cp -r static/configurations/. site/static/wallpapers/
          cp -r static/backgrounds/. site/static/backgrounds/
          cp -r static/examples/. site/static/examples

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: site/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
