name: Deploy Dart Web App

on:
  push:
    branches:
      - generator-dart
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install Dependencies
        run: |
          cd dart/web
          dart pub get

      - name: Compile Dart to JavaScript
        run: |
          cd dart/web
          dart compile js -o main.js main.dart

      - name: Move files to deployment directory
        run: |
          # Creiamo la cartella "site" che conterrà i file da deployare
          mkdir -p site/static/logos
          mkdir -p site/static/octocats
          cp dart/web/index.html site/
          cp dart/web/main.js site/
          cp dart/web/styles.css site/
          cp -a Logos/. site/static/logos/
          cp -a Octocats/. site/static/octocats/

      - name: Fix file permissions
        run: chmod -R a+rX site

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # L'azione si aspetta che l'artefatto sia chiamato "github-pages"
          # Di default il nome è impostato correttamente, basta fornire il path
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
