name: Deploy Dart Web App

on:
  push:
    branches:
      - generator-dart

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install Dependencies
        run: |
          cd dart/web
          dart pub get

      - name: Compile Dart to JavaScript
        run: |
          cd dart/web
          dart compile js -o main.js main.dart

      - name: Move files to deployment directory
        run: |
          mkdir public
          cp -r dart/web/index.html public/
          cp -r dart/web/main.js public/
          cp -r dart/web/styles.css public/
          mkdir public/static/
          mkdir public/static/logos
          cp -r Logos/* public/static/logos
          mkdir public/static/octocats
          cp -r Octocats/* public/static/octocats

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dart/web/
          clean: true

    name: Deploy Dart Web to GitHub Pages
    
