name: Deploy Dart Web App

on:
  push:
    branches:
      - generator-dart

  # Abilita il deploy automatico
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install Dependencies
        run: |
          cd dart/web
          dart pub get

      - name: Compile Dart to JavaScript
        run: |
          cd dart/web
          dart compile js -o main.js main.dart

      - name: Move files to deployment directory
        run: |
          mkdir public
          cp -r dart/web/index.html public/
          cp -r dart/web/main.js public/
          cp -r dart/web/styles.css public/
          mkdir public/static/
          mkdir public/static/logos
          cp -r Logos/* public/static/logos
          mkdir public/static/octocats
          cp -r Octocats/* public/static/octocats

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

    deploy:
      needs: build
      runs-on: ubuntu-latest
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2