name: Deploy Dart Web App

on:
  push:
    branches:
      - generator-dart
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install Dependencies
        run: |
          cd dart/web
          dart pub get

      - name: Compile Dart to JavaScript
        run: |
          cd dart/web
          dart compile js -o main.js main.dart

      - name: Move files to deployment directory
        run: |
          mkdir -p public/static/logos
          mkdir -p public/static/octocats
          cp dart/web/index.html public/
          cp dart/web/main.js public/
          cp dart/web/styles.css public/
          cp -a Logos/. public/static/logos/
          cp -a Octocats/. public/static/octocats/

      # Flatten the deployment directory into a temporary "artifact" folder
      - name: Flatten deployment directory for artifact
        run: |
          rm -rf artifact
          mkdir artifact
          cp -rL public/* artifact/
          # Remove any symlinks if present (just in case)
          find artifact -type l -exec rm {} \;
          echo "Contents of artifact directory:"
          find artifact

      # Set proper permissions for all files in the artifact folder
      - name: Set file permissions for artifact
        run: chmod -R a+rX artifact

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: artifact/**

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: artifact

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
